version: "3.3"
services:
  mysql-server:
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf:/etc/mysql
    environment:
      - TZ=Asia/Hong_Kong
      - MYSQL_ROOT_PASSWORD=12345678
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis1-server:
    container_name: redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis/redis1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Hong_Kong
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  redis2-server:
    container_name: redis2
    image: redis:latest
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./redis/redis2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Hong_Kong
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  zk-server:
    container_name: zookeeper
    image: wurstmeister/zookeeper ## 镜像
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./zookeeper/conf:/conf
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    environment:
      - TZ=Asia/Hong_Kong
  # https://www.jianshu.com/p/1d7759d77ec1
  kafka:
    image: wurstmeister/kafka ## 镜像
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 8.129.173.10 ## 修改:宿主机IP
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_LOG_RETENTION_HOURS: 120
      # KAFKA_MESSAGE_MAX_BYTES: 10000000
      # KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      # KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      # KAFKA_NUM_PARTITIONS: 3
      # KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #       - 8051:80
  #       - 8043:443
  #   volumes:
  #       - ./nginx/dist:/usr/share/nginx/html
  #       - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #       - ./nginx/conf/conf.d:/etc/nginx/conf.d
  #   environment:
  #       - TZ=Asia/Hong_Kong
  bu-admin:
    container_name: admin
    image: tomcat:8-jdk8
    restart: always
    ports:
      - 9090:8080
    volumes:
      - ./app/tomcat8_admin/webapps:/usr/local/tomcat/webapps
      - ./app/tomcat8_admin/conf:/usr/local/tomcat/conf
      - ./app/tomcat8_admin/logs:/usr/local/tomcat/logs
    environment:
      - TZ=Asia/Hong_Kong
  mongo-container:
    image: mongo:3.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27018:27017"
    volumes:
      - "./mongo/db:/data/db"
      - "./mongo/entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
