version: "3.3"
services:
  ce-mysql:
    container_name: ce-mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ce-mysql-5.6:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=12345678
      - /etc/localtime:/etc/localtime
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ce-redis1:
    container_name: ce-redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis/redis1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  ce-redis2:
    container_name: ce-redis2
    image: redis:latest
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./redis/redis2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  ce-zookeeper:
    container_name: ce-zookeeper
    image: wurstmeister/zookeeper ## 镜像
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./zookeeper/conf:/conf
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    environment:
      - TZ=Asia/Shanghai
  # https://www.jianshu.com/p/1d7759d77ec1
  # https://blog.csdn.net/Crystalqy/article/details/94006936
  ce-kafka:
    container_name: ce-kafka
    image: wurstmeister/kafka ## 镜像
    ports:
      - "9083:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22 ## 修改:宿主机IP
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: ce-zookeeper:2181
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_LOG_RETENTION_HOURS: 120
      # KAFKA_MESSAGE_MAX_BYTES: 10000000
      # KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      # KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      # KAFKA_NUM_PARTITIONS: 3
      # KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  ce-kafka-manager:
    container_name: ce-kafka-manager
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: ce-zookeeper:2181
  ce-mongo:
    container_name: ce-mongo
    image: mongo:3.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27018:27017"
    volumes:
      - "./mongo/db:/data/db"
      - "./mongo/entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
  ######## ce-app
  ce-app-cloud:
    container_name: ce-app-cloud
    image: openjdk:8
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./app/cloud/cloud.jar:/cloud.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=7000 -Dspring.profiles.active=dev /cloud.jar

  ce-app-ucenter-api:
    container_name: ce-app-ucenter-api
    image: openjdk:8
    restart: always
    ports:
      - 9001:6001
    volumes:
      - ./app/ucenter-api/ucenter-api.jar:/ucenter-api.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6001 -Dspring.profiles.active=dev /ucenter-api.jar
  ce-app-exchange-api:
    container_name: ce-app-exchange-api
    image: openjdk:8
    restart: always
    ports:
      - 9003:6003
    volumes:
      - ./app/exchange-api/exchange-api.jar:/exchange-api.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6003 -Dspring.profiles.active=dev /exchange-api.jar
  ce-app-exchange:
    container_name: ce-app-exchange
    image: openjdk:8
    restart: always
    ports:
      - 9005:6005
    volumes:
      - ./app/exchange/exchange.jar:/exchange.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6005 -Dspring.profiles.active=dev /exchange.jar
  ce-app-admin:
    container_name: ce-app-admin
    image: openjdk:8
    restart: always
    ports:
      - 9010:6010
    volumes:
      - ./app/admin/admin-api.jar:/admin-api.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6010 -Dspring.profiles.active=dev /admin-api.jar
  ce-app-open-api:
    container_name: ce-app-open-api
    image: openjdk:8
    restart: always
    ports:
      - 9011:7010
    volumes:
      - ./app/open-api/open-api.jar:/open-api.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=7010 -Dspring.profiles.active=dev /open-api.jar
  ce-app-chat:
    container_name: ce-app-chat
    image: openjdk:8
    restart: always
    ports:
      - 9008:6008
    volumes:
      - ./app/chat/chat.jar:/chat.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6008 -Dspring.profiles.active=dev /chat.jar    
  ce-app-market:
    container_name: ce-app-market
    image: openjdk:8
    restart: always
    ports:
      - 9004:6004
    volumes:
      - ./app/market/market.jar:/market.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6004 -Dspring.profiles.active=dev /market.jar    
  ce-app-otc-api:
    container_name: ce-app-otc-api
    image: openjdk:8
    restart: always
    ports:
      - 9006:6006
    volumes:
      - ./app/otc-api/otc-api.jar:/otc-api.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=6006 -Dspring.profiles.active=dev /otc-api.jar
  ce-app-wallet:
    container_name: ce-app-wallet
    image: openjdk:8
    restart: always
    ports:
      - 9007:7006
    volumes:
      - ./app/wallet/wallet.jar:/wallet.jar
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=7006 -Dspring.profiles.active=dev /wallet.jar

  ######## ce-web
  ce-web-admin:
    container_name: ce-web-admin
    image: nginx:latest
    restart: always
    ports:
      - 8090:80
    volumes:
      - ./app/web-admin/dist:/usr/share/nginx/html
      - ./nginx/web-admin/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/web-admin/conf/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
  ce-web-web:
    container_name: ce-web-web
    image: nginx:latest
    restart: always
    ports:
      - 8091:80
    volumes:
      - ./app/web-web/dist:/usr/share/nginx/html
      - ./nginx/web-web/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/web-web/conf/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
volumes:
  ce-mysql-5.6:
