version: "3.3"
services:
  mysql-server:
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3308:3306
    volumes:
      - /data/coinexchange/db/mysql_data:/var/lib/mysql
      - /data/coinexchange/db/mysql_conf:/etc/mysql
    environment:
      - TZ=Asia/Hong_Kong
      - MYSQL_ROOT_PASSWORD=12345678
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
