version: "3.3"
services:
  mysql-server:
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf:/etc/mysql
    environment:
      - TZ=Asia/Hong_Kong
      - MYSQL_ROOT_PASSWORD=12345678
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis1-server:
    container_name: redis1
    image: redis:latest
    restart: always
    ports:
        - 6380:6379
    volumes:
        - ./redis/redis1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - TZ=Asia/Hong_Kong
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  redis2-server:
    container_name: redis2
    image: redis:latest
    restart: always
    ports:
        - 6381:6379
    volumes:
        - ./redis/redis2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - TZ=Asia/Hong_Kong
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
  zk-server:
    container_name: zookeeper
    container_name: zookeeper
    image: zookeeper:latest
    restart: always
    ports:
        - 2182:2181
    volumes:
        - ./zookeeper/conf:/conf
    environment:
        - TZ=Asia/Hong_Kong
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #       - 8051:80
  #       - 8043:443
  #   volumes:
  #       - ./nginx/dist:/usr/share/nginx/html
  #       - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #       - ./nginx/conf/conf.d:/etc/nginx/conf.d
  #   environment:
  #       - TZ=Asia/Hong_Kong        
  bu-admin:
    container_name: admin
    image: tomcat:8-jdk8
    restart: always
    ports:
        - 9090:8080
    volumes:
        - ./app/tomcat8_admin/webapps:/usr/local/tomcat/webapps
        - ./app/tomcat8_admin/conf:/usr/local/tomcat/conf
        - ./app/tomcat8_admin/logs:/usr/local/tomcat/logs
    environment:
        - TZ=Asia/Hong_Kong        
  mongo-container:
      image: mongo:3.4
      container_name: mongodb
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
      ports:
        - "27018:27017"
      volumes:
        - "./mongo/db:/data/db"
        - "./mongo/entrypoint/:/docker-entrypoint-initdb.d/"
      command: mongod