version: "3"
services:
  ce-mysql:
    container_name: ce-mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ce-mysql-5.6:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=12345678
      - /etc/localtime:/etc/localtime
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      extnetwork:
  ce-redis1:
    container_name: ce-redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis/redis1/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
    networks:
      extnetwork:
  ce-redis2:
    container_name: ce-redis2
    image: redis:latest
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./redis/redis2/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
    networks:
      extnetwork:
  ce-zookeeper:
    container_name: ce-zookeeper
    image: wurstmeister/zookeeper ## 镜像
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./zookeeper/conf:/conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
  # https://www.jianshu.com/p/1d7759d77ec1
  # https://blog.csdn.net/Crystalqy/article/details/94006936
  ce-kafka:
    container_name: ce-kafka
    image: wurstmeister/kafka ## 镜像
    ports:
      - "9083:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${url_host} ## 修改:宿主机IP
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: ce-zookeeper:2181
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_LOG_RETENTION_HOURS: 120
      # KAFKA_MESSAGE_MAX_BYTES: 10000000
      # KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      # KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      # KAFKA_NUM_PARTITIONS: 3
      # KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    networks:
      extnetwork:
  ce-kafka-manager:
    container_name: ce-kafka-manager
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: ce-zookeeper:2181
    networks:
      extnetwork:
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
  ce-mongo:
    container_name: ce-mongo
    image: mongo:3.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27018:27017"
    volumes:
      - "./mongo/db:/data/db"
      - "./mongo/entrypoint/:/docker-entrypoint-initdb.d/"
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    command: mongod
    networks:
      extnetwork:

  ######## ce-app
  ce-app-cloud:
    container_name: ce-app-cloud
    image: openjdk:8
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./app/cloud/:/app/
      - ./logs:/mnt/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/cloud.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo

  ce-app-ucenter-api:
    container_name: ce-app-ucenter-api
    image: openjdk:8
    restart: always
    ports:
      - 9001:6001
    volumes:
      - ./app/ucenter-api/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/ucenter-api.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-exchange-api:
    container_name: ce-app-exchange-api
    image: openjdk:8
    restart: always
    ports:
      - 9003:6003
    volumes:
      - ./app/exchange-api/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/exchange-api.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-exchange:
    container_name: ce-app-exchange
    image: openjdk:8
    restart: always
    ports:
      - 9005:6005
    volumes:
      - ./app/exchange/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/exchange.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-cloud

  ce-app-admin-api:
    container_name: ce-app-admin-api
    image: openjdk:8
    restart: always
    ports:
      - 9010:6010
    volumes:
      - ./app/admin-api/admin-api.jar:/app/admin-api.jar
      - ./app/admin-api/lib:/app/lib
      - ./app/admin-api/config:/app/config
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/admin-api.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-open-api:
    container_name: ce-app-open-api
    image: openjdk:8
    restart: always
    ports:
      - 9011:7010
    volumes:
      - ./app/open-api/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/open-api.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-chat:
    container_name: ce-app-chat
    image: openjdk:8
    restart: always
    ports:
      - 9008:6008
      - 28902:28902
    volumes:
      - ./app/chat/:/app/
      - ./logs:/mnt/logs/
      - ./app/chat/web/:/web/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/chat.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-market:
    container_name: ce-app-market
    image: openjdk:8
    restart: always
    ports:
      - 9004:6004
      - 28901:28901
    volumes:
      - ./app/market/market.jar:/app/market.jar
      - ./app/market/lib:/app/lib
      - ./app/market/config:/app/config
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/market.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-cloud

  ce-app-otc-api:
    container_name: ce-app-otc-api
    image: openjdk:8
    restart: always
    ports:
      - 9006:6006
    volumes:
      - ./app/otc-api/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/otc-api.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-app-wallet:
    container_name: ce-app-wallet
    image: openjdk:8
    restart: always
    ports:
      - 9007:7006
    volumes:
      - ./app/wallet/:/app/
      - ./logs:/mnt/logs/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Duser.dir=/app/ -Xms512m -Xmx512m -Dloader.path=/app/lib,/app/config -jar /app/wallet.jar
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

  ce-nginx:
    container_name: ce-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./web/web-web/dist:/web/web-web/dist
      - ./web/web-admin/dist:/web/web-admin/dist
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
    depends_on:
      - ce-mysql
      - ce-redis1
      - ce-redis2
      - ce-zookeeper
      - ce-kafka
      - ce-kafka-manager
      - ce-mongo
      - ce-app-exchange
      - ce-app-cloud
      - ce-app-market

volumes:
  ce-mysql-5.6:

networks:
  extnetwork:
    ipam:
      config:
        - subnet: ${subnet}